# Generated by Django 2.1.1 on 2018-09-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180901_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='ponto_turisticos'),
        ),
    ]
